In [1]:
import numpy as np
import sympy as sp

In [13]:
#Old version withOUT ref frequency
def Omega_gw_func(f):
    return 1e-6 * (f) **(5)

In [2]:

def Omega_gw_func(f, f0):
    return 1e-6 * (f/f0) **(3)

In [14]:
#Old version: No refrence freq
def angular_fluc(Omega_gw, gE,gB, frequency, HubbleConstant):
    H=HubbleConstant/3.08567758128e+19
    print("Hubble Constant in 1/s:", H)
    f=sp.Symbol('f')
    
    alpha = np.array([0.833333, 0.116667, 0.03, 0.0104762, 0.00442177, 0.00212585, 0.00112434, 0.000639731, 0.000385675, 0.000243696])
    
    def sigma(freq): #Defining sigma or the power distro in frequency f
        integral=sp.integrate((f**-3) * Omega_gw(f),f)
        sigma_val=(Omega_gw(freq) * freq**-2) * (integral.subs(f,freq))**-1
        print("Sigma:", sigma_val)
        return float(sigma_val)
        
    
    def theta_rms(freq): #Defining theta RMS which is the total power in angular fluctuations
        integral=sp.integrate((f**-3)*(H**2 * Omega_gw(f)),f)
        theta_rms_square=float(((4 * np.pi**2)**-1) * integral.subs(f,freq))
        print("Theta rms:", np.sqrt(theta_rms_square))
        return np.sqrt(theta_rms_square)
    
    #Calculating the numerical value for sigma and theta_rms given the frequency
    sigma_val=sigma(frequency)
    theta_rms_val=theta_rms(frequency)
    
    theta_E=np.sqrt(theta_rms_val**2 * gE * sigma_val * alpha)
    theta_B=np.sqrt(theta_rms_val**2 * gB * sigma_val * alpha)
    return theta_E , theta_B

In [12]:
def angular_fluc(Omega_gw, gE,gB, frequency, ref_freq, HubbleConstant):
    H=HubbleConstant/3.08567758128e+19
    print("Hubble Constant in 1/s:", H)
    f=sp.Symbol('f')
    f0=ref_freq
    
    alpha = np.array([0.833333, 0.116667, 0.03, 0.0104762, 0.00442177, 0.00212585, 0.00112434, 0.000639731, 0.000385675, 0.000243696])
    
    if isinstance(frequency, list) and len(frequency) ==1 or isinstance(frequency, float):
        if isinstance(frequency, list):
            frequency=frequency[0]
        
        if frequency<0:
            Max_freq=0
            Min_freq=frequency
        else:
            Max_freq=frequency
            Min_freq=0
            
    else:
        Max_freq=np.amax(frequency)
        Min_freq=np.amin(frequency)
    
        
    #Defining sigma or the power distro in frequency f
    def sigma(Max_freq,Min_freq): 
        integral=sp.integrate((f**-3) * Omega_gw(f,f0), (f, Min_freq, Max_freq)) #<----changed with ref freq
        sigma_val=(Omega_gw(f, f0) * f**-2) * (integral)**-1
        print("Sigma:", sigma_val)
        return sigma_val
        
    #Defining theta RMS which is the total power in angular fluctuations
    def theta_rms(Max_freq, Min_freq): 
        integral=sp.integrate((f**-3)*(H**2 * Omega_gw(f,f0)),(f, Min_freq, Max_freq)) #<----changed with ref freq
        theta_rms_square=((4 * np.pi**2)**-1) * integral
        print("Theta rms square:", theta_rms_square)
        return theta_rms_square    
        
    #should theta E and theta B be a function of f. Should we plug in a value for f? if so do we use ref?
    
    
    #Calculating the numerical value for sigma and theta_rms given the frequency
    sigma_val=sigma(Max_freq,Min_freq)
    theta_rms_val_square=theta_rms(Max_freq,Min_freq)
    
    theta_E_square=theta_rms_val_square * gE * sigma_val * alpha
    theta_B_square=theta_rms_val_square * gB * sigma_val * alpha
    return theta_E_square , theta_B_square

In [15]:
#Old version: No ref freq
angular_fluc(Omega_gw_func,0.5,0.5,1e-9,70)

Hubble Constant in 1/s: 2.2685455027664497e-18
Sigma: 3.00000000000000
Theta rms: 6.591845185977466e-36


(array([7.36990549e-36, 2.75757062e-36, 1.39834153e-36, 8.26331901e-37,
        5.36847213e-37, 3.72236484e-37, 2.70708230e-37, 2.04197926e-37,
        1.58548951e-37, 1.26030839e-37]),
 array([7.36990549e-36, 2.75757062e-36, 1.39834153e-36, 8.26331901e-37,
        5.36847213e-37, 3.72236484e-37, 2.70708230e-37, 2.04197926e-37,
        1.58548951e-37, 1.26030839e-37]))

In [14]:
angular_fluc(Omega_gw_func,0.5,0.5,[1e-9],1e-9,70)

Hubble Constant in 1/s: 2.2685455027664497e-18
1e-09 0
Sigma: 1000000000.0*f
Theta rms: 1.30357268867683e-25


(array([5.43155069686563e-17*f, 7.60419574349297e-18*f,
        1.95535903301524e-18*f, 6.82824410055809e-19*f,
        2.88204930380527e-19*f, 1.38560000011182e-19*f,
        7.32829458393452e-20*f, 4.16967929849958e-20*f,
        2.51377698352718e-20*f, 1.58837724969894e-20*f], dtype=object),
 array([5.43155069686563e-17*f, 7.60419574349297e-18*f,
        1.95535903301524e-18*f, 6.82824410055809e-19*f,
        2.88204930380527e-19*f, 1.38560000011182e-19*f,
        7.32829458393452e-20*f, 4.16967929849958e-20*f,
        2.51377698352718e-20*f, 1.58837724969894e-20*f], dtype=object))

In [11]:
#Old Angular fluc velocity
def angular_fluc_vel(Omega_gw, gE,gB, frequency, HubbleConstant):
    H=HubbleConstant/3.08567758128e+19
    print("Hubble Constant in 1/s:", H)
    f=sp.Symbol('f')
    
    alpha = np.array([0.833333, 0.116667, 0.03, 0.0104762, 0.00442177, 0.00212585, 0.00112434, 0.000639731, 0.000385675, 0.000243696])
    
    
    def sigma(freq): #Defining sigma or the power distro in frequency f
        integral=sp.integrate((f**-3) * Omega_gw(f),f)
        sigma_val=(Omega_gw(freq) * freq**-2) * (integral.subs(f,freq))**-1
        print("Sigma:", sigma_val)
        return float(sigma_val)
    
    def theta_rms_dot(freq):
        integral=sp.integrate((f**-1) * (H**2) * (Omega_gw(f)), f)
        theta_rms_dot_square=integral.subs(f,freq)
        print(theta_rms_dot_square)
        print("Theta rms:", np.sqrt(theta_rms_dot_square))
        return np.sqrt(theta_rms_dot_square)
    
    #Calculating the numerical value for sigma and theta_rms given the frequency
    sigma_val=sigma(frequency)
    theta_rms_dot_val=theta_rms_dot(frequency)
    
    theta_E_dot=np.sqrt(theta_rms_dot_val**2 * gE * sigma_val * alpha)
    theta_B_dot=np.sqrt(theta_rms_dot_val**2 * gB * sigma_val * alpha)
    return theta_E_dot , theta_B_dot
        

In [15]:
def angular_fluc_vel(Omega_gw, gE, gB, frequency, ref_freq, HubbleConstant):
    H=HubbleConstant/3.08567758128e+19
    print("Hubble Constant in 1/s:", H)
    f=sp.Symbol('f')
    f0=ref_freq
    alpha = np.array([0.833333, 0.116667, 0.03, 0.0104762, 0.00442177, 0.00212585, 0.00112434, 0.000639731, 0.000385675, 0.000243696])
    
    if isinstance(frequency, list) and len(frequency) ==1 or isinstance(frequency, float):
        if isinstance(frequency, list):
            frequency=frequency[0]
        
        if frequency<0:
            Max_freq=0
            Min_freq=frequency
        else:
            Max_freq=frequency
            Min_freq=0
            
    else:
        Max_freq=np.amax(frequency)
        Min_freq=np.amin(frequency)

    def sigma(Max_freq,Min_freq): 
        integral=sp.integrate((f**-3) * Omega_gw(f,f0), (f, Min_freq, Max_freq)) #<----changed with ref freq
        sigma_val=(Omega_gw(f, f0) * f**-2) * (integral)**-1
        print("Sigma:", sigma_val)
        return sigma_val
    
    def theta_rms_dot(Max_freq, Min_freq):
        integral=sp.integrate((f**-1) * (H**2) * (Omega_gw(f,f0)), (f,Min_freq,Max_freq))
        theta_rms_dot_square=integral
        print("Theta rms square:", theta_rms_dot_square)
        return theta_rms_dot_square
    
    #Calculating the numerical value for sigma and theta_rms given the frequency
    sigma_val=sigma(Max_freq, Min_freq)
    theta_rms_dot_val_square=theta_rms_dot(Max_freq, Min_freq)
    
    theta_E_dot_square=theta_rms_dot_val_square * gE * sigma_val * alpha
    theta_B_dot_square=theta_rms_dot_val_square * gB * sigma_val * alpha
    return theta_E_dot_square , theta_B_dot_square

In [16]:
angular_fluc_vel(Omega_gw_func,0.5,0.5,1e-9,1e-9,70)

Hubble Constant in 1/s: 2.2685455027664497e-18
Sigma: 1000000000.0*f
Theta rms square: 1.71543289937396e-42


(array([7.14763422167001e-34*f, 1.00067205035631e-34*f,
        2.57314934906094e-35*f, 8.98560907021074e-36*f,
        3.7926248657324e-36*f, 1.82337651456707e-36*f,
        9.6436491304106e-37*f, 5.48707802074702e-37*f,
        3.30799791733026e-37*f, 2.09022067922918e-37*f], dtype=object),
 array([7.14763422167001e-34*f, 1.00067205035631e-34*f,
        2.57314934906094e-35*f, 8.98560907021074e-36*f,
        3.7926248657324e-36*f, 1.82337651456707e-36*f,
        9.6436491304106e-37*f, 5.48707802074702e-37*f,
        3.30799791733026e-37*f, 2.09022067922918e-37*f], dtype=object))